// .templates/frontend/react/src/App.tsx
import {useEffect, useState} from 'react'
import ValuecaseLogo from "./assets/valuecase_logo_plain_back.png"
import './App.css'
import axios from "axios";
import FileUploadExample from "./FileUploadExample";

function App() {
  const [apiAvailable, setApiAvailable] = useState<boolean | undefined>(undefined)

  useEffect(() => {
      let stopped = false

      axios.get("/api").then(() => {
          if ( stopped ) return
          setApiAvailable(true)
      }).catch(() => {
          if ( stopped ) return
          setApiAvailable(false)
      })

      const interval = setInterval(() => {
        axios.get("/api").then(() => {
            setApiAvailable(true)
        }).catch(() => {
            setApiAvailable(false)
        })
      }, 1000)

      return () => {
          stopped = true
          clearInterval(interval)
      }
  })

  return (
      <div className={"centeringContainer"}>
          <div className={"card"}>
              <img className={"logo"} src={ValuecaseLogo}/>
              <div className={"welcome"}>Tech Challenge – React ⚛️</div>
              <hr/>
              <div>API available: {apiAvailable === undefined ? '⏳' : apiAvailable ? '✅' : '❌'}</div>

              {apiAvailable && <>
                  <hr />
                  <FileUploadExample />
              </>}
          </div>
      </div>
  )
}

export default App

// .templates/frontend/angular/src/app/app.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import axios from "axios"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit, OnDestroy {
  apiAvailable: boolean | null = null
  apiCheckInterval: number | undefined = undefined

  ngOnInit(): void {
    axios.get("/api").then(() => {
      this.apiAvailable = true
    }).catch(() => {
      this.apiAvailable = false
    })

    this.apiCheckInterval = setInterval(() => {
      axios.get("/api").then(() => {
        this.apiAvailable = true
      }).catch(() => {
        this.apiAvailable = false
      })
    }, 1000)
  }

  ngOnDestroy(): void {
    clearInterval(this.apiCheckInterval)
  }


}

<div class="centeringContainer">
  <div class="card">
    <img class="logo" src="assets/valuecase_logo_plain_back.png"/>
    <div class="welcome">Tech Challenge – Angular 🛡</div>
    <hr/>
    <div>API available: {{apiAvailable === null ? '⏳' : apiAvailable ? '✅' : '❌'}}</div>

    <ng-template [ngIf]="apiAvailable === true">
      <hr />
      <app-file-upload-example />
    </ng-template>
  </div>
</div>
