// .templates/frontend/vue/src/FileUploadExample.vue
<script setup lang="ts">
import {reactive, ref} from "vue";
import {FileUpload, uploadFile} from "./uploadFile";

  const state = reactive<{
    fileToUpload?: File,
    fileUpload?: FileUpload
  }>({})

  const form = ref<HTMLFormElement | null>(null)

  function inputChanged(e: Event) {
    const input = e.target as HTMLInputElement | undefined
    if ( input && input.files && input.files.length > 0 ) {
      state.fileToUpload = input.files[0]
    }
  }

  function handleFileUpload(e: Event) {
    e.preventDefault()
    if ( state.fileToUpload ) {
      uploadFile(state.fileToUpload)
          .then(res => {
            state.fileUpload = res
            state.fileToUpload = undefined
            form.value?.reset()
          })
    }
  }
</script>

<template>
  <form ref="form" @submit="handleFileUpload">
    <input type="file" @input="inputChanged"/>
    <br />
    <br />
    <button v-if="state.fileToUpload" type="submit">Upload file ⬆️</button>
  </form>

  <div v-if="state.fileUpload">
    <hr>
    File-ID: {{state.fileUpload?.fileId}}
    <br />
    File-Path: <a :href="state.fileUpload?.filePath" target="_blank">{{state.fileUpload?.filePath}}</a>
  </div>
</template>

// .templates/frontend/angular/src/app/file-upload-example/file-upload-example.component.ts
import {Component, ViewChild, ElementRef} from '@angular/core';
import {FormControl, FormGroup} from '@angular/forms';
import {FileUpload, uploadFile} from "../../uploadFile";

@Component({
  selector: 'app-file-upload-example',
  templateUrl: './file-upload-example.component.html',
})
export class FileUploadExampleComponent {
  @ViewChild('fileInput') fileInput: ElementRef | null = null;

  fileToUpload: File | null = null
  fileUpload: FileUpload | null = null

  onFileInput(e: Event) {
    const input = (e.target as HTMLInputElement | undefined)
    if ( input && input.files && input.files.length > 0 ) {
      this.fileToUpload = input.files[0]
      this.fileUpload = null
    } else {
      this.fileToUpload = null
    }
  }

  handleFileUpload(e: Event) {
    e.preventDefault()

    if ( this.fileToUpload ) {
      uploadFile(this.fileToUpload)
        .then((result) => {
          this.fileUpload = result
          this.fileToUpload = null

          if ( this.fileInput ) {
            this.fileInput.nativeElement.value = ""
          }
        })
    }
  }
}

<form (submit)="handleFileUpload($event)">
  <input #fileInput name="file" type="file" (input)="onFileInput($event)">
  <br />
  <br />

  <ng-template [ngIf]="!!fileToUpload">
    <button type="submit">Upload file ⬆️</button>
  </ng-template>
</form>

<div *ngIf="!!fileUpload">
  <hr />
  File-ID: {{fileUpload.fileId}}
  <br />
  File-Path: <a [href]="fileUpload.filePath" target="_blank">{{fileUpload.filePath}}</a>
</div>
