// .templates/frontend/vue/src/App.vue
<script setup lang="ts">
import FileUploadExample from "./FileUploadExample.vue";
import {onBeforeUnmount, onMounted, reactive} from "vue";
import axios from "axios";

const state = reactive<{apiAvailable?: boolean, interval?: number}>({})

onMounted(() => {
  axios.get("/api")
      .then(() => { state.apiAvailable = true })
      .catch(() => { state.apiAvailable = false })

  state.interval = setInterval(() => {
    axios.get("/api")
        .then(() => { state.apiAvailable = true })
        .catch(() => { state.apiAvailable = false })
  }, 1000)
})

onBeforeUnmount(() => {
  clearInterval(state.interval)
})
</script>

<template>
  <div class="centeringContainer">
    <div class="card">
      <img class="logo" src="src/assets/valuecase_logo_plain_back.png"/>
      <div class="welcome">Tech Challenge – Vue 👀</div>
      <hr/>
      <div>API available: {{ state.apiAvailable === undefined ? '⏳' : state.apiAvailable ? '✅' : '❌'}}</div>

      <template v-if="state.apiAvailable">
        <hr>
        <FileUploadExample />
      </template>
    </div>
  </div>
</template>

<style scoped>
.centeringContainer {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
}

.card {
  border-radius: 8px;
  padding: 24px;
  box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  display: flex;
  flex-direction: column;
  gap: 16px;
  align-items: center;
  background: white;
  min-width: 30rem;
  max-width: 99%;
}

.welcome {
  font-size: 1.3rem;
}

.logo {
  max-height: 2rem;
}
</style>

// .templates/frontend/react/src/App.tsx
import {useEffect, useState} from 'react'
import ValuecaseLogo from "./assets/valuecase_logo_plain_back.png"
import './App.css'
import axios from "axios";
import FileUploadExample from "./FileUploadExample";

function App() {
  const [apiAvailable, setApiAvailable] = useState<boolean | undefined>(undefined)

  useEffect(() => {
      let stopped = false

      axios.get("/api").then(() => {
          if ( stopped ) return
          setApiAvailable(true)
      }).catch(() => {
          if ( stopped ) return
          setApiAvailable(false)
      })

      const interval = setInterval(() => {
        axios.get("/api").then(() => {
            setApiAvailable(true)
        }).catch(() => {
            setApiAvailable(false)
        })
      }, 1000)

      return () => {
          stopped = true
          clearInterval(interval)
      }
  })

  return (
      <div className={"centeringContainer"}>
          <div className={"card"}>
              <img className={"logo"} src={ValuecaseLogo}/>
              <div className={"welcome"}>Tech Challenge – React ⚛️</div>
              <hr/>
              <div>API available: {apiAvailable === undefined ? '⏳' : apiAvailable ? '✅' : '❌'}</div>

              {apiAvailable && <>
                  <hr />
                  <FileUploadExample />
              </>}
          </div>
      </div>
  )
}

export default App
