// .templates/frontend/vue/src/FileUploadExample.vue
<script setup lang="ts">
import {reactive, ref} from "vue";
import {FileUpload, uploadFile} from "./uploadFile";

  const state = reactive<{
    fileToUpload?: File,
    fileUpload?: FileUpload
  }>({})

  const form = ref<HTMLFormElement | null>(null)

  function inputChanged(e: Event) {
    const input = e.target as HTMLInputElement | undefined
    if ( input && input.files && input.files.length > 0 ) {
      state.fileToUpload = input.files[0]
    }
  }

  function handleFileUpload(e: Event) {
    e.preventDefault()
    if ( state.fileToUpload ) {
      uploadFile(state.fileToUpload)
          .then(res => {
            state.fileUpload = res
            state.fileToUpload = undefined
            form.value?.reset()
          })
    }
  }
</script>

<template>
  <form ref="form" @submit="handleFileUpload">
    <input type="file" @input="inputChanged"/>
    <br />
    <br />
    <button v-if="state.fileToUpload" type="submit">Upload file ⬆️</button>
  </form>

  <div v-if="state.fileUpload">
    <hr>
    File-ID: {{state.fileUpload?.fileId}}
    <br />
    File-Path: <a :href="state.fileUpload?.filePath" target="_blank">{{state.fileUpload?.filePath}}</a>
  </div>
</template>

// .templates/frontend/react/src/FileUploadExample.tsx
import {FormEvent, useCallback, useRef, useState} from "react";
import {FileUpload, uploadFile} from "./uploadFile";

export default function FileUploadExample() {
    const formRef = useRef<HTMLFormElement | null>(null)
    const [fileToUpload, setFileToUpload] = useState<File | null>(null)
    const [fileUpload, setFileUpload] = useState<FileUpload | null>(null)

    const fileCallback = useCallback((e: FormEvent<HTMLInputElement>) => {
        const input = (e.target as HTMLInputElement | undefined)
        if ( input && input.files && input.files.length > 0 ) {
            setFileToUpload(input.files[0])
        } else {
            setFileToUpload(null)
        }
    }, [])

    const handleFileUpload = useCallback((e: FormEvent) => {
        e.preventDefault()
        if ( fileToUpload ) {
            uploadFile(fileToUpload)
                .then((result) => {
                    setFileUpload(result)
                    setFileToUpload(null)
                    formRef.current?.reset()
                })
        }
    }, [fileToUpload])

    return <>
        <form ref={formRef} onSubmit={handleFileUpload}>
            <input type="file" onInput={fileCallback}/>
            <br />
            <br />
            {fileToUpload && <button type={"submit"}>Upload file ⬆️</button>}
        </form>

        {fileUpload && <div>
            <hr />
            File-ID: {fileUpload.fileId}
            <br />
            File-Path: <a href={fileUpload.filePath} target={"_blank"}>{fileUpload.filePath}</a>
        </div>}
    </>
}
